# vi:ft=nginx
# Redirect all HTTP requests to HTTPS by default.
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	access_log	/var/log/nginx/80-default.log main_ext;

	# Allow stub status from localhost
	include prefabs.d/stub-status.conf;

	# Allow ACME challenge
	include prefabs.d/acme-challenge.conf;

	# Configure error pages
	error_page 404 /40x.html;
	error_page 501 502 503 504 /50x.html;
	location ~ /(40x|50x)\.html$ {
		root /usr/local/nginx/html;
	}

	location / {
		return 404;
		break;
	}
}

