# Enable nginx stub status
server {
    listen 127.0.0.1:80;
    listen [::1]:80;
    server_name 127.0.0.1;
    location /nginx_status {
        stub_status;
	    access_log off;
        allow 127.0.0.1;
	    allow ::1;
        deny all;
    }
}
