# vim:ft=nginx

# http://wordpress.example/ => https://www.wordpress.example/
server {
	listen 80;
	server_name	www.wordpress.example wordpress.example;

	# Accept the ACME challenge from Let's Encrypt
	include prefabs.d/acme-challenge.conf;

	location / {
		return 301 https://www.wordpress.example$request_uri;
		break;
	}
}

# https://www.wordpress.example/
server {
	listen 443 ssl http2;
	server_name	www.wordpress.example wordpress.example;
	root /home/wordpressexample/www
	index index.php;

	ssl_certificate /usr/local/etc/ssl/cert.pem;
	ssl_certificate_key	/usr/local/etc/ssl/key.pem;
	include prefabs.d/tls-modern.conf;

	access_log /var/log/nginx/www.wordpress.example-access.log main_ext;
	error_log /var/log/nginx/www.wordpress.example-error.log error;

	include prefabs.d/general-wordpress.conf;

	location ~ [^/]\.php(/|$) {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		include nginx.d/defaults/fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
		fastcgi_pass unix:/var/run/php-fpm/php-fpm-www.wordpress.example.sock;
	}
}

