# If these buffers are to small to contain the request body or header,
# the buffer is written to a temp file.
client_body_buffer_size 	128k;
client_header_buffer_size	1k;

# Close connection if client tries to post a body size larger than this. 413 error is sent
client_max_body_size		64m;
large_client_header_buffers     8 	10k;
output_buffers			1	32k;
postpone_output			1460;

