# Default NGiNX log format, for reference
# log_format combined 	'$remote_addr - $remote_user [$time_local] '
#        		'"$request" $status $body_bytes_sent '
#			'"$http_referer" "$http_user_agent"';

# Dump the request body. Note that the request body is not read by nginx unless 
# the data is destined for a proxy_pass or fastcgi_pass
log_format dumper	'$remote_addr - $remote_user [$time_local] "$request" $status '
			'$body_bytes_sent "$http_referer" "$http_user_agent" Body: "$request_body"';

# Display more proxy related things such as headers
log_format proxy	'$remote_addr - $remote_user [$time_local] '
        		'"$request" $status $body_bytes_sent '
			'"$http_referer" "$http_user_agent" '
			'X-Forwarded-For=$http_x_forwarded_for Host=$host $request_id';

# Extended nginx logging used with nginx-amplify
log_format  main_ext  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" '
                      '"$host" sn="$server_name" '
                      'rt=$request_time '
                      'ua="$upstream_addr" us="$upstream_status" '
                      'ut="$upstream_response_time" ul="$upstream_response_length" '
                      'cs=$upstream_cache_status';

# Human readable logging
log_format pretty   '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status '
                    '"$http_referer" ';
