# These should all be enabled. sendfile and tcp_nopush ensures that
# the packets are full before being sendt to the client, when it reaches
# the last packet NGiNX removes the tcp_nopush so that tcp_nodelay
# can force the socket to send the data immediately.

# Turning sendfile on will cause nginx to use the senfile(2) syscall when sending files
# to clients. sendfile(2) enables copying data between file descriptors entirely within
# kernel space instead of using read(2) and write(2) to transfer the data - using nginx's
# application memory as an unnecessary intermediary.
#
# Calling syscalls from user space will also cause a context switch to kernel space which
# is relatively expensive. sendfile requires that tcp_nopush is enabled
sendfile		on;

# TCP_CORK blocks the data until the packet reaches the MSS, 
# which equals to the MTU minus the 40 or 60 bytes of the IP header.
# This option leads to more throughput and less network overhead.
tcp_nopush		on;

# TCP_NODELAY forces a socket to send the data in its buffer. This
# avoids Nagle's algorithm which can lead to a 200ms delay.
# This obviously leads to less latency, up to 200ms per request.
tcp_nodelay		on;

