# How long will the server wait for the client header or client body to be sent after the request?
# If neither is received within the respective timers, a 408 Request Timed Out error will be sent
client_header_timeout		10;
client_body_timeout		10;

# The duration of keepalive connections; The server will close the connection after this long
keepalive_timeout		15;

# The time between two operations of reading, if after this time the client doesnt accept
# more data the connection is closed
send_timeout			6;

